{{- if .Values.rbac.create }}
apiVersion: {{ include "common_redis.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "common_redis.names.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels: {{- include "common_redis.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common_redis.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common_redis.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common_redis.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "redis.serviceAccountName" . }}
{{- end }}
