{{- $host := include "common_redis.names.fullname" . }}
{{- if not .Values.sentinel.enabled }}
{{- $host = printf "%s-master" (include "common_redis.names.fullname" .) }}
{{- end }}
{{- $port := print .Values.master.service.ports.redis }}
{{- if .Values.sentinel.enabled }}
{{- $port = print .Values.sentinel.service.ports.redis }}
{{- end }}
{{- $password := include "redis.password" . }}

{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common_redis.names.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels: {{- include "common_redis.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common_redis.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
      {{- if .Values.secretAnnotations }}
      {{- include "common_redis.tplvalues.render" ( dict "value" .Values.secretAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
      {{- include "common_redis.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
  {{- end }}
type: Opaque
data:
  redis-password: {{ print $password | b64enc | quote }}
{{- end -}}
{{- if .Values.serviceBindings.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common_redis.names.fullname" . }}-svcbind
  namespace: {{ .Values.namespace | quote }}
  labels: {{- include "common_redis.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common_redis.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common_redis.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: servicebinding.io/redis
data:
  provider: {{ print "bitnami" | b64enc | quote }}
  type: {{ print "redis" | b64enc | quote }}
  host: {{ print $host | b64enc | quote }}
  port: {{ print $port | b64enc | quote }}
  password: {{ print $password | b64enc | quote }}
  uri: {{ printf "redis://%s@%s:%s" $password $host $port | b64enc | quote }}
{{- end }}
