{{- if .Values.serviceAccounts.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.server" . }}
{{ include "prometheus.namespace" . | indent 2 }}
  annotations:
  {{- if .Values.global.monitoring.integrations.amp.enabled }}
    eks.amazonaws.com/role-arn: "{{.Values.global.monitoring.integrations.amp.ingest_role_arn}}" 
  {{- end }}
{{- end }}
