apiVersion: v1
kind: Service
metadata:
  name: copilot-conversation-manager
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: copilot-conversation-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}