apiVersion: v1
kind: ServiceAccount
metadata:
  name: rafay-pipeline-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rafay-pipeline-role
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    verbs:
    - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rafay-pipeline-rb
subjects:
- kind: ServiceAccount
  name: rafay-pipeline-sa
  namespace: rafay-core
roleRef:
  kind: Role
  name: rafay-pipeline-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rafay-pipeline
  name: rafay-pipeline
spec:
{{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: rafay-pipeline
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rafay-pipeline
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rafay-pipeline
              topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: RPC_PORT
          valueFrom:
            configMapKeyRef:
              key: rpcPort
              name: rafay-pipeline-configmap
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              key: apiPort
              name: rafay-pipeline-configmap
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: dbName
              name: rafay-pipeline-configmap
        - name: SECRET_PATH
          valueFrom:
            configMapKeyRef:
              key: secretPath
              name: rafay-pipeline-configmap
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: dbUser
              name: rafay-pipeline-configmap
        - name: DB_ADDR
          valueFrom:
            configMapKeyRef:
              key: dbAddr
              name: rafay-pipeline-configmap
        {{- if .Values.global.is_external_database }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pipelinedb-db-secret
        {{- else }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pipelinedbuser.postgres-admin.credentials.postgresql.acid.zalan.do
        {{- end }}
        - name: SCHEDULER_ADDR
          valueFrom:
            configMapKeyRef:
              key: schedulerAddr
              name: rafay-pipeline-configmap
        - name: CONFIG_ADDR
          valueFrom:
            configMapKeyRef:
              name: rafay-pipeline-configmap
              key: configAddr
        - name: DEV
          valueFrom:
            configMapKeyRef:
              key: dev
              name: rafay-pipeline-configmap
        - name: AUTH_ADDR
          valueFrom:
            configMapKeyRef:
              key: authAddr
              name: rafay-pipeline-configmap
        - name: SENTRY_ADDR
          valueFrom:
            configMapKeyRef:
              key: sentry.addr
              name: rafay-pipeline-configmap
        - name: CRYPTO_ADDR
          valueFrom:
            configMapKeyRef:
              key: crypto.addr
              name: rafay-pipeline-configmap
        - name: INFRA_PROVISIONER_ADDR
          valueFrom:
            configMapKeyRef:
              key: infra.provisioner.addr
              name: rafay-pipeline-configmap
        - name: CORE_CD_AGENT_ADDR
          valueFrom:
            configMapKeyRef:
              key: cdagent.core.addr
              name: rafay-pipeline-configmap
        - name: CD_RELAY_USER_HOST
          valueFrom:
            configMapKeyRef:
              key: cdrelay.user.host
              name: rafay-pipeline-configmap
        - name: SEND_GRID_API_KEY
          valueFrom:
            secretKeyRef:
              key: sendgrid.apikey
              name: rafay-pipeline-secret
        - name: INTERNAL_TRIGGER_PORT                        
          valueFrom:                                          
            configMapKeyRef:                                  
              key: internal.trigger.port                      
              name: rafay-pipeline-configmap                  
        - name: HUB_ADDR                                      
          valueFrom:                                          
            configMapKeyRef:                                  
              key: hub.addr                                   
              name: rafay-pipeline-configmap                  
        - name: INTERNAL_TRIGGER_ENDPOINT                     
          valueFrom:                                          
            configMapKeyRef:                                  
              key: internal.trigger.endpoint                  
              name: rafay-pipeline-configmap                  
        - name: CACHE_GROUP_PORT                              
          valueFrom:                                          
            configMapKeyRef:                                  
              key: groupcache.port                            
              name: rafay-pipeline-configmap
       {{- if .Values.global.ssl_mode }}
        - name: PGSSLMODE
          value: {{ default "" .Values.global.ssl_mode }}
       {{- end }}
        image: {{ .Values.rafay_pipeline_image }}
        name: rafay-pipeline
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }} 
      serviceAccount: rafay-pipeline-sa
---
{{- if .Values.global.ha_enabled }}
{{- if ne .Values.global.size "S" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: rafay-pipeline
  name: rafay-pipeline
spec:
  maxReplicas: {{ default "10" .Values.maxReplicas }}
{{- if eq .Values.global.ha_enabled true }}
  minReplicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  minReplicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rafay-pipeline
  targetCPUUtilizationPercentage: 80
{{- end }}
{{- end }}