---
apiVersion: v1
kind: Service
metadata:
  name: rafay-pipeline
spec:
  ports:
  - name: grpc
    port: 7000
    protocol: TCP
    targetPort: 13000
  - name: http-pipeline
    port: 8000
    protocol: TCP
    targetPort: 14000
  - name: tcp-notification
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: tcp-internal                                            
    port: 9001                                                
    protocol: TCP                                             
    targetPort: 9001
  selector:
    app: rafay-pipeline
  type: ClusterIP
---                                                           
apiVersion: v1                                                
kind: Service                                                 
metadata:                                                     
  name: pipeline-cache-group                                  
spec:                                                         
  clusterIP: None                                             
  ports:                                                      
  - protocol: TCP                                           
    name: tcp-cache                                             
    port: 8080                                              
    targetPort: 8080                                        
  selector:                                                   
    app: rafay-pipeline
