apiVersion: apps/v1
kind: Deployment
metadata:
  name: salt-exec
  labels:
    app: salt-exec
spec:
{{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: salt-exec
  template:
    metadata:
      labels:
        app: salt-exec
    spec:
      containers:
        - name: salt-exec
          image: {{ .Values.salt_exec_image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-port
              containerPort: 8000
              protocol: TCP
          env:
            - name: PG_HOST
              value: postgres-admin
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: edgedb
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  key: edge.db.user
                  name: edgesrv-secrets
            - name: SALT_PG_HOST
              value: postgres-admin
            - name: SALT_PG_PORT
              value: "5432"
            - name: SALT_PG_DATABASE
              value: saltdb
            - name: SALT_PG_USERNAME
              value: {{ .Values.global.dbusers.salt_db_user }}
          {{- if .Values.global.is_external_database }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: edgedb-db-secret
            - name: SALT_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: saltdb-db-secret
          {{- else }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: edgedbuser.postgres-admin.credentials.postgresql.acid.zalan.do
            - name: SALT_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: saltdbuser.postgres-admin.credentials.postgresql.acid.zalan.do
            - name: SALT_MASTER_HOST
              value: infra-salt-orchestrator-ext.rafay-core.svc.cluster.local
            - name: SALT_HA_ENABLED
              value: "true"
            - name: INFRA_SALT_ROUTER_HOST
              value: infra-salt-router.rafay-core.svc.cluster.local
            - name: INFRA_SALT_ROUTER_PORT
              value: "4600"
          {{- end }}
          {{- if .Values.global.ssl_mode }}
            - name: PGSSLMODE
              value: {{ default "" .Values.global.ssl_mode }}
          {{- end }}
          {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
          resources:
            limits:
              cpu: "{{ .Values.cpu_limits }}"
              memory: "{{ .Values.memory_limits }}"
            requests:
              cpu: "{{ .Values.cpu_requests }}"
              memory: "{{ .Values.memory_requests }}"
          {{- end }} 
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
              scheme: HTTP

---
{{- if .Values.global.ha_enabled }}
{{- if ne .Values.global.size "S" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: salt-exec
  name: salt-exec
spec:
  maxReplicas: {{ default "10" .Values.maxReplicas }}
{{- if eq .Values.global.ha_enabled true }}
  minReplicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  minReplicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: salt-exec
  targetCPUUtilizationPercentage: 80
{{- end }}
{{- end }}
