apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
  labels:
    prometheus: k8s
  name: k8s
spec:
  baseImage: "{{ .Values.prometheus_image }}"
  evaluationInterval: 1m
  externalLabels:
    prometheus: rafay-infra/k8s
  externalUrl: https://prometheusrelay.ops.stage.rafay-edge.net
  logLevel: debug
  nodeSelector:
    beta.kubernetes.io/os: linux
  query:
    lookbackDelta: 1m
  remoteRead:
  - readRecent: true
    remoteTimeout: 1m
    url: http://promscale-connector.rafay-core.svc.cluster.local:9201/read?db=monitoringdb&rp=shortterm&u=opsuser&p=Rafay!49
  replicas: 1
  {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
  resources:
    limits:
      cpu: "{{ .Values.cpu_limits }}"
      memory: "{{ .Values.memory_limits }}"
    requests:
      cpu: "{{ .Values.cpu_requests }}"
      memory: "{{ .Values.memory_requests }}"
  {{- end }}    
  retention: 24h
  scrapeInterval: 1m
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchExpressions:
    - key: none
      operator: Exists
  version: v2.31.1
