apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: k8s
  type: ClusterIP
