apiVersion: v1
kind: Service
metadata:
  name: edge-processor
spec:
  ports:
    - protocol: TCP
      name: grpc
      port: 60001
      targetPort: 60001
    - protocol: TCP
      name: http-edge-processor
      port: 8000
      targetPort: 8000
  selector:
    app: edge-processor
