apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-nexus
spec:
  {{- if eq .Values.global.isCustomRegistry true}} 
  host: nexus-service.rafay-registry.svc.cluster.local
  {{- else }}
  host: nexus-service.rafay-core.svc.cluster.local
  {{- end }}
  trafficPolicy:
    tls:
      mode: DISABLE
