apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  name: nexus-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    name: http-nexus
    targetPort: 8081
  - port: 5000
    protocol: TCP
    name: tcp-docker
    targetPort: 80
  selector:
    app: nexus-server
  type: ClusterIP


