kafka:
  broker:
    persistence:
      enabled: true
      size: 200Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi

  zookeeper:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      enabled: true
      size: 10Gi