{{- if .Values.global.tsdb_backupr_enabled }}
{{- if eq .Values.global.deployment_type "GKE" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-gcs-key
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "timescaledb-helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/resource-policy": keep 
type: Opaque
stringData:
  gcs-key.json: {{ .Values.tsdb_backup.gcs_key | b64dec | quote }}
{{- end }}
{{- end }}
