# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
{{- if eq .Values.secrets.pgbackrestSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secrets_pgbackrest" $ }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "timescaledb-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbackrest
  annotations:
    "helm.sh/hook-weight": "0"
type: Opaque
{{- if and (.Release.IsUpgrade) (ne (len .Values.secrets.pgbackrest) 0) }}
data: {{ (lookup "v1" "Secret" .Values.namespace (include "secrets_pgbackrest" .)).data }}
{{- else }}
stringData:
{{- if .Values.global.tsdb_backup_enabled }}
{{- if eq .Values.global.deployment_type "EKS" }}
PGBACKREST_REPO1_S3_REGION: "{{ .Values.global.tsdb.bucket_region }}"
PGBACKREST_REPO1_S3_BUCKET: "{{ .Values.global.tsdb.tsdb_backup_bucket }}"
PGBACKREST_REPO1_S3_ENDPOINT: "s3.{{ .Values.global.tsdb.bucket_region }}.amazonaws.com"
PGBACKREST_REPO1_S3_ROLE: "{{ .Values.global.tsdb.tsdb_backup_role_arn }}"
PGBACKREST_REPO1_S3_KEY_TYPE: "web-id"
{{- end }}
{{- if eq .Values.global.deployment_type "GKE" }}
PGBACKREST_REPO1_GCS_BUCKET: "{{ .Values.global.tsdb.tsdb_backup_bucket }}"
PGBACKREST_REPO1_GCS_ENDPOINT: "storage.googleapis.com"
PGBACKREST_REPO1_GCS_KEY: "/etc/pgbackrest/gcs-key/gcs-key.json"
PGBACKREST_REPO1_GCS_KEY_TYPE: "service"
{{- end }}
{{- end }}   
{{- end }}
...
{{- end }}
