apiVersion: v1
kind: Service
metadata:
  name: copilot-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: copilot-service
  sessionAffinity: None
  type: ClusterIP