apiVersion: v1
kind: Service
metadata:
  name: rafay-workflow-helpers
  namespace: rafay-core
spec:
  ports:
  - name: grpc
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rafay-workflow-helpers
  type: ClusterIP