image: registry.rafay-edge.net/timescale/promscale:0.17.0
image_cronjob_maintenance: registry.rafay-edge.net/postgres:16.2
connection:
   dbName: &metricDB postgres
   # user to connect to TimescaleDB with
   user: PATRONI_SUPERUSER_PASSWORD
   password:
     # Name of a secret object (templated) containing the connection password
     # Key must be value of promscale.connection.user
     # Created by default if timescaledb-single.enabled=true
     secretTemplate: &dbPassSecret "rafay-tsdb-credentials"
   host:
     # Host name (templated) of the database instance, default
     # to service created in timescaledb-single
     nameTemplate: &dbHost "rafay-tsdb.rafay-core.svc.cluster.local"
   port: 5432
   sslMode: disable
prometheus:
  enabled: true
  # Using the predefined annotations from the Prometheus helm chart:
  # https://hub.helm.sh/charts/stable/prometheus
  annotations:
    traffic.sidecar.istio.io/excludeInboundPorts: "5432"
    traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9201'
    prometheus.io/path: '/metrics'
