---
apiVersion: v1
kind: Service
metadata:
  name: rafay-kiali
spec:
  ports:
  - name: http
    port: 20001
    protocol: TCP
    targetPort: 20001
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: rafay-kiali
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
