podLabels:
  customLableA: Aaaaa
imageRenderer:
  enabled: true
  env:
    RENDERING_ARGS: --disable-gpu,--window-size=1280x758
    RENDERING_MODE: clustered
  podLabels:
    customLableB: Bbbbb
  networkPolicy:
    limitIngress: true
    limitEgress: true
  {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
  resources:
    limits:
      cpu: "{{ .Values.cpu_limits }}"
      memory: "{{ .Values.memory_limits }}"
    requests:
      cpu: "{{ .Values.cpu_requests }}"
      memory: "{{ .Values.memory_requests }}"
  {{- end }}