---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capi-controller-eksa-bm-sa
  namespace: rafay-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rafay-core
  name: capi-controller-eksa-bm-role
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    verbs:
    - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-controller-eksa-bm-rb
  namespace: rafay-core
subjects:
  - kind: ServiceAccount
    name: capi-controller-eksa-bm-sa
    namespace: rafay-system
roleRef:
  kind: Role
  name: capi-controller-eksa-bm-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: capi-controller-eksa-bm
  name: capi-controller-eksa-bm
  namespace: rafay-core
spec:
  progressDeadlineSeconds: 600
  {{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
  {{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: capi-controller-eksa-bm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capi-controller-eksa-bm
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: 
                      - capi-controller-eksa-bm
              topologyKey: kubernetes.io/hostname
      serviceAccount: "capi-controller-eksa-bm-sa"
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INFRA_RELAY_USER_HOST
          valueFrom:
            configMapKeyRef:
              key: infrarelay.user.host
              name: capi-controller-eksa-bm-configmap
        - name: SENTRY_ADDR
          valueFrom:
            configMapKeyRef:
              key: sentry.addr
              name: capi-controller-eksa-bm-configmap
        - name: OVA_TEMPLATE_S3_URL
          valueFrom:
            configMapKeyRef:
              key: ova.template.s3.url
              name: capi-controller-eksa-bm-configmap
        - name: NEXUS_URL
          valueFrom:
            configMapKeyRef:
              key: nexus.url
              name: capi-controller-eksa-bm-configmap
        - name: GITHUB_TOKEN
          valueFrom:
            configMapKeyRef:
              key: github.token
              name: capi-controller-eksa-bm-configmap
        image: {{.Values.capi_controller_eksa_bm_image }}
        imagePullPolicy: IfNotPresent
        name: capi-controller-eksa-bm
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }}      