apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Chart.Name}}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Chart.Name}}-role
rules:
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: interests-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: interests-role
subjects:
  - kind: ServiceAccount
    name: interests-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interests
  name: interests
spec:
{{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: interests
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: interests
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - interests
              topologyKey: kubernetes.io/hostname
      serviceAccount: interests-sa              
      containers:
      - name: interests
        image: "{{ .Values.global.envmgr_image }}"
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }}        
        env:
        - name: INTEREST_ENABLE_API
          valueFrom:
            configMapKeyRef:
              key: interest.enable_api
              name: interests-cm
        - name: INTEREST_API_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: interest.interest_api.db_host
              name: interests-cm
        - name: INTEREST_API_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: interest.interest_api.db_name
              name: interests-cm
        - name: INTEREST_API_DB_USER
          valueFrom:
            configMapKeyRef:
              key: interest.interest_api.db_user
              name: interests-cm
        {{- if .Values.global.is_external_database }}  
        - name: INTEREST_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: interestsdb-db-secret
        {{- else }} 
        - name: INTEREST_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: interestsdbuser.postgres-admin.credentials.postgresql.acid.zalan.do
        {{- end}} 
        - name: LEADER_ELECTION_LEADER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LEADER_ELECTION_LEASE_LOCK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEADER_ELECTION_LEASE_LOCK_NAME
          value: "interests-lock"
        livenessProbe:
          httpGet:
            path: /livez
            port: 15010
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 15010
          periodSeconds: 10
          successThreshold: 3
          failureThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 5  