{{- if and .Values.serviceAccount.create .Values.amp_enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sigv4-proxy.serviceAccountName" . }}
  labels:
    {{- include "sigv4-proxy.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.amp_enabled}}
  annotations:
    {{- if .Values.amp_enabled }}
    eks.amazonaws.com/role-arn: "{{ .Values.prometheus.integrations.amp.ingest_role_arn}}" 
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
