apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controller-selfsigned-cert
spec:
  dnsNames:
    - control.core.{{ .Values.global.default_partner_console_domain }}
  secretName: selfsigned-cert-tls-scheduler
  duration: 87600h
  renewBefore: 12h
  issuerRef:
    name: self-signed-infar-ca-issuer
