apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: debug-broker-selfsigned-cert
spec:
  dnsNames:
    - debug.core.{{ .Values.global.default_partner_console_domain }}
  secretName: selfsigned-cert-tls-debug-broker
  duration: 87600h
  renewBefore: 12h
  issuerRef:
    name: self-signed-infar-ca-issuer


