apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: salt-selfsigned-cert
spec:
  dnsNames:
    - salt.core.{{ .Values.global.default_partner_console_domain }}
  secretName: selfsigned-infra-salt-orchestrator-cert-tls
  duration: 87600h
  renewBefore: 12h
  issuerRef:
    name: self-signed-salt-ca-issuer
