apiVersion: v1
kind: ServiceAccount
metadata:
  name: eaas-api-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eaas-api-role
rules:
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eaas-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eaas-api-role
subjects:
  - kind: ServiceAccount
    name: eaas-api-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eaas-api
  name: eaas-api
spec:
{{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: eaas-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eaas-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - eaas-api
              topologyKey: kubernetes.io/hostname     
      serviceAccount: eaas-api-sa
      containers:
      - name: eaas-api
        image: "{{ .Values.global.envmgr_image }}"
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }}        
        env:
        - name: EAAS_API_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas_api.redis_addr
              name: eaas-api-cm
        - name: EAAS_API_CACHE_PROVIDER
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas_api.cache_provider
              name: eaas-api-cm
        - name: EAAS_API_SKIP_TLS_VERIFY
          value: "true"
        - name: EAAS_ENABLE_API
          valueFrom:
            configMapKeyRef:
              key: eaas.enable_api
              name: eaas-api-cm
        - name: HELPERS_ADDR
          valueFrom:
            configMapKeyRef:
              key: helpers.addr
              name: eaas-api-cm
        - name: EAAS_API_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas_api.db_host
              name: eaas-api-cm
        - name: EAAS_API_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas_api.db_name
              name: eaas-api-cm
        - name: EAAS_API_DB_USER
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas_api.db_user
              name: eaas-api-cm
        {{- if .Values.global.is_external_database }}  
        - name: EAAS_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: eaasdb-db-secret
        {{- else }} 
        - name: EAAS_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: eaasdbuser.postgres-admin.credentials.postgresql.acid.zalan.do
        {{- end}}      
        - name: REGISTRY_FQDN
          valueFrom:
            configMapKeyRef:
              key: registry.fqdn
              name: eaas-api-cm
        - name: ARTIFACT_DRIVER_IMAGE
          valueFrom:
            configMapKeyRef:
              key: artifact.driver.image
              name: eaas-api-cm
        - name: TF_DRIVER_IMAGE
          valueFrom:
            configMapKeyRef:
              key: tf.driver.image
              name: eaas-api-cm
        - name: INTERESTS_SERVICE_RPC_ADDR
          valueFrom:
            configMapKeyRef:
              key: interests_service.rpc_addr
              name: eaas-api-cm
        - name: EAAS_API_ENGINE_RPC_ADDR
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas_api.engine_rpc_addr
              name: eaas-api-cm
        - name: EAAS_API_APPROVALS_RPC_ADDR
          valueFrom:
            configMapKeyRef:
              key: eaas.eaas.api.approvals_rpc_addr
              name: eaas-api-cm
        - name: LEADER_ELECTION_LEADER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LEADER_ELECTION_LEASE_LOCK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEADER_ELECTION_LEASE_LOCK_NAME
          value: "eaas-api-lock"
        livenessProbe:
          httpGet:
            path: /livez
            port: 15010
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 15010
          periodSeconds: 10
          successThreshold: 3
          failureThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 5  
