apiVersion: v1
kind: ConfigMap
metadata:
  name: eaas-api-cm
data:
  eaas.eaas_api.redis_addr: redis-master:6379
  eaas.eaas_api.cache_provider: redis
  eaas.enable_api: "true"
  helpers.addr: "rafay-workflow-helpers:8000"
  eaas.eaas_api.db_host: postgres-admin
  eaas.eaas_api.db_user: eaasdbuser
  eaas.eaas_api.db_name: eaasdb
  eaas.eaas_api.engine_rpc_addr: engine-api:5000
  eaas.eaas.api.approvals_rpc_addr: approvals:9000
  interests_service.rpc_addr: interests:7000
  {{- if eq .Values.global.isCustomRegistry true}} 
  registry.fqdn: "ops-console.{{ .Values.global.default_partner_console_domain }}/rafay"
  {{- else }} 
  registry.fqdn: "ops-console.{{ .Values.global.default_partner_console_domain }}"
  {{- end }}
  artifact.driver.image: rafay/{{ (splitList "/" .Values.global.artifact_driver_image) | last }} 
  tf.driver.image: rafay/{{ (splitList "/" .Values.global.tf_driver_image) | last }}  

