apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "connector.fullname" . | trunc 51 }}-maintenance
  namespace: {{ .Values.namespace }}  
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.maintenance.schedule }}
  startingDeadlineSeconds: {{ .Values.maintenance.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.maintenance.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.maintenance.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: {{ .Chart.Name }}-maintenance
            image: {{ .Values.image_cronjob_maintenance }}
            args:
            - sh
            - ./execute_maintenance.sh
            env:
              {{- if not .Values.connection.uri.secretTemplate }}
              - name: PGPORT
                value: "5432"
              - name: PGUSER
                value: postgres
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.connection.password.secretTemplate . }}
                    key: {{ .Values.connection.user }}
              - name: PGHOST
                value: {{ tpl .Values.connection.host.nameTemplate . }}
              - name:  PGDATABASE
                value: {{ .Values.connection.dbName }}
              {{- else }}
              - name: PROMSCALE_DB_URI
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.connection.uri.secretTemplate . }}
                    key: {{ .Values.connection.uri.key }}
              {{- end }}
            volumeMounts:
              - name: script-volume
                mountPath: /execute_maintenance.sh
                subPath: execute_maintenance.sh
              - name: script-volume
                mountPath: /truncate_series.sql
                subPath: truncate_series.sql
          volumes:
            - name: script-volume
              configMap:
                name: {{ include "connector.fullname" . | trunc 51 }}-maintenance
          restartPolicy: OnFailure
