apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector.fullname" . | trunc 53 }}-connector
  namespace: {{ .Values.namespace }}  
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ .Values.service.loadBalancer.annotations | toYaml | indent 4 }}
spec:
  selector:
    app: {{ template "connector.fullname" . }}
{{- if .Values.service.loadBalancer.enabled }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
  - name: http-promscale-connector
    port: {{ .Values.service.port }}
    protocol: TCP
