---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infra-salt-router
  name: infra-salt-router
spec:
  {{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
  {{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: infra-salt-router
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "443"
      labels:
        app: infra-salt-router
    spec:
      containers:
      - env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              key: edge.db.user
              name: infra-salt-router-secrets
        {{- if .Values.global.is_external_database }}
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: edgedb-db-secret
        {{- else }}
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: edgedbuser.postgres-admin.credentials.postgresql.acid.zalan.do
        {{- end }}
        - name: PG_DATABASE
          value: edgedb
        - name: PG_HOST
          value: postgres-admin
        - name: PG_PORT
          value: "5432"
        - name: REDIS_HOST
          value: admin-redis
        - name: REDIS_ADDRESS
          value: "redis-master:6379"
        - name: REDIS_PORT
          value: "6379"
        image: {{.Values.infra_salt_router_image }}
        imagePullPolicy: IfNotPresent
        name: infra-salt-router
        ports:
        - containerPort: 4600
          protocol: TCP
        - containerPort: 4700
          protocol: TCP
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}
            memory: {{ .Values.memory_limits }}
          requests:
            cpu: {{ .Values.cpu_requests }}
            memory: {{ .Values.memory_requests }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: infra-salt-router-sa
      serviceAccountName: infra-salt-router-sa
      terminationGracePeriodSeconds: 10