gateways:
  istio-ingressgateway:
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 400Mi  

pilot:
  # Resources for a small pilot install
  resources:
    requests:
      cpu: 1m
      memory: 1Mi

global:
  defaultResources:
    requests:
      cpu: 1m

  proxy:
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

spec:
  selector:
    spec:
      containers:
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
