{
 "title": "Cluster Scheduler Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "scheduler_db_idle_connections",
   "type": "graph",
   "description": "Number of idle database connections",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_db_idle_connections", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "scheduler_db_stale_connections",
   "type": "graph",
   "description": "Number of stale database connections",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_db_stale_connections", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "scheduler_db_tot_connections",
   "type": "graph",
   "description": "Number of total database connections",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_db_tot_connections", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "scheduler_free_placement_workers",
   "type": "graph",
   "description": "Number of workers currently unused",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_free_placement_workers",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "scheduler_tot_antientropy_placement_events_processed",
   "type": "graph",
   "description": "Total number of placement events processed",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_tot_antientropy_placement_events_processed",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "scheduler_tot_placement_events_pending",
   "type": "graph",
   "description": "Number of placement events that are pending",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_tot_placement_events_pending",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "scheduler_tot_placement_events_processed",
   "type": "graph",
   "description": "Total number of placement events processed",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_tot_placement_events_processed",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "scheduler_tot_placement_events_retry",
   "type": "graph",
   "description": "Number of placement events that are pending",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_tot_placement_events_retry",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "scheduler_used_placement_workers",
   "type": "graph",
   "description": "Number of workers currently being used",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_used_placement_workers",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } }
 ]
}