{
 "title": "Rafay Relay Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "cluster_cnt",
   "type": "graph",
   "description": "No of cluster connected to this relay server",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cluster_cnt ", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "cluster_conn_cnt",
   "type": "graph",
   "description": "cluster_conn_cnt No of cluster connection to this relay server",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cluster_conn_cnt", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "relay_req_cnt",
   "type": "graph",
   "description": "Number of request received by this relay server",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "relay_req_cnt", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}