---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capability-api-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capability-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capability-api-role
subjects:
  - kind: ServiceAccount
    name: capability-api-sa