apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
data:
  rpcPort: "5000"
  apiAddr: api.{{ .Values.global.default_partner_console_domain }}
  apiPort: "8000"
  authAddr: authsrv.rafay-core.svc.cluster.local:50011
  configAddr: "rafay-config:7000"
  peerPort: "5001"
  connectorPort: "5002"
  dbAddr: "postgres-admin:5432"
  dbName: "clusterdb"
  dbUser: {{ .Values.global.dbusers.cluster_db_user }}
  secretPath: "/opt/rcloud/certs"
  dev: "false"
  controlAddr: control.core.{{ .Values.global.default_partner_console_domain }}
  sentryAddr: rafay-sentry:7000
  sentryBootstrapAddr: console.{{ .Values.global.default_partner_console_domain }}:443
  enablePprof: "false"
  helm3TempPath: /tmp
  cryptoAddr: "cryptosvc:50505"
  edgeAddr: "edgesrv:50701"
  tsAddr: "traffic-steering:50001"
  redisAddr: "{{ .Values.global.redis_endpoint  }}.rafay-core.svc.cluster.local:6379"
  tracingEnabled: "false"
  tracingDSN: ""
  VAULTINIT_IMAGE: {{ (splitList "/" .Values.global.vaultinit_image) | last | quote }}
  SECRETSTOREHOOK_IMAGE: {{ (splitList "/" .Values.global.secretstorehook_image) | last | quote }}
  CONTROLLER_IMAGE: {{ (splitList "/" .Values.global.cluster_controller_image) | last | quote }}
  CONNECTOR_IMAGE: {{ (splitList "/" .Values.global.cluster_connector_image) | last | quote }}
  CDAGENT_IMAGE: {{ (splitList "/" .Values.global.rafay_cd_agent_image) | last | quote }}
  EDGECLIENT_IMAGE: {{ (splitList "/" .Values.global.edge_client_image) | last | quote }}
  {{- if eq .Values.global.isCustomRegistry true }}
  relayAgentImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/rafay/{{ (splitList "/" .Values.global.rafay_relay_agent_image) | last }}
  busyBoxImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/rafay/{{ (splitList "/" .Values.global.busyBoxImage) | last }} 
  connectorImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/rafay/{{ (splitList "/" .Values.global.cluster_connector_image) | last }}
  controllerImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/rafay/{{ (splitList "/" .Values.global.cluster_controller_image) | last }}
  {{- else }}
  relayAgentImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/{{ (splitList "/" .Values.global.rafay_relay_agent_image) | last }}
  busyBoxImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/{{ (splitList "/" .Values.global.busyBoxImage) | last }}
  connectorImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/{{ (splitList "/" .Values.global.cluster_connector_image) | last }}
  controllerImage: ops-console.{{ .Values.global.default_partner_console_domain }}/rafay/{{ (splitList "/" .Values.global.cluster_controller_image) | last }} 
  {{- end }}
