---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: cluster-scheduler  
spec:
  ports:
    - protocol: TCP
      name: tcp-rpc
      port: 5000
      targetPort: 5000
    - protocol: TCP
      name: tcp-cluster
      port: 5002
      targetPort: 5002
    - protocol: TCP
      name: grpc-peerport
      port: 5001
      targetPort: 5001
    - protocol: TCP
      name: http-api
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: 2112      
  selector:
    app: cluster-scheduler
