global:
  ha_enabled: true
image:
  repository: registry.rafay-edge.net/acid/postgres-operator:v1.10.1
  pullPolicy: "IfNotPresent"
configGeneral:
  docker_image: registry.rafay-edge.net/acid/spilo-15:3.1-p1
configLogicalBackup:
  logical_backup_docker_image: registry.rafay-edge.net/acid/logical-backup:v1.10.0
configConnectionPooler:
  connection_pooler_image: registry.rafay-edge.net/acid/pgbouncer:master-32
