---
apiVersion: v1
kind: Service
metadata:
  name: keygensvc
spec:
  ports:
    - protocol: TCP
      name: grpc-internal
      port: 50505
      targetPort: 50505
  selector:
    app: keygensvc

---
