---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: saltmaster-etc-salt-pki
spec:
{{- if eq .Values.global.ha_enabled true }}
 {{- if eq .Values.global.deployment_type "AIRGAP" }}
 storageClassName: {{ .Values.global.storageClass }}
 {{- else }}
 {{- if .Release.IsUpgrade }}
 storageClassName: {{ (lookup "v1" "PersistentVolumeClaim" "rafay-core" "saltmaster-etc-salt-pki").spec.storageClassName }}
 {{ else }}
 storageClassName: {{ .Values.global.storageClass }}
 {{ end }}
 {{- end }}
 accessModes:
  - ReadWriteOnce
{{- else }}
 {{- if .Release.IsUpgrade }}
 storageClassName: {{ (lookup "v1" "PersistentVolumeClaim" "rafay-core" "saltmaster-etc-salt-pki").spec.storageClassName }}
 {{ else }}
 storageClassName: {{ .Values.global.storageClass }}
 {{ end }}
 accessModes:
  - ReadWriteOnce
{{- end }}
 resources:
   requests:
     storage: {{ .Values.saltmaster_etc_salt_pki_volume_size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: saltmaster-srv-salt
spec:
{{- if eq .Values.global.ha_enabled true }}
 {{- if eq .Values.global.deployment_type "AIRGAP" }}
 storageClassName: {{ .Values.global.storageClass }}
 {{- else }}
 {{- if .Release.IsUpgrade }}
 storageClassName: {{ (lookup "v1" "PersistentVolumeClaim" "rafay-core" "saltmaster-srv-salt").spec.storageClassName }}
 {{ else }}
 storageClassName: {{ .Values.global.storageClass }}
 {{ end }}
 {{ end }}
 accessModes:
  - ReadWriteOnce
{{- else }}
 {{- if .Release.IsUpgrade }}
 storageClassName: {{ (lookup "v1" "PersistentVolumeClaim" "rafay-core" "saltmaster-srv-salt").spec.storageClassName }}
 {{ else }}
 storageClassName: {{ .Values.global.storageClass }}
 {{ end }}
 accessModes:
  - ReadWriteOnce
{{- end }}
 resources:
   requests:
     storage: {{ .Values.saltmaster_srv_salt_volume_size }}

---
#saltmaster-conf-volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: saltmaster-conf-volume
 
spec:
{{- if eq .Values.global.ha_enabled true }}
 {{- if eq .Values.global.deployment_type "AIRGAP" }}
 storageClassName: {{ .Values.global.storageClass }}
 {{- else }}
 {{- if .Release.IsUpgrade }}
 storageClassName: {{ (lookup "v1" "PersistentVolumeClaim" "rafay-core" "saltmaster-conf-volume").spec.storageClassName }}
 {{ else }}
 storageClassName: {{ .Values.global.storageClass }}
 {{ end }}
 {{ end }}
 accessModes:
  - ReadWriteOnce
{{- else }}
 {{- if .Release.IsUpgrade }}
 storageClassName: {{ (lookup "v1" "PersistentVolumeClaim" "rafay-core" "saltmaster-conf-volume").spec.storageClassName }}
 {{ else }}
 storageClassName: {{ .Values.global.storageClass }}
 {{ end }}
 accessModes:
  - ReadWriteOnce
{{- end }}
 resources:
   requests:
     storage: {{ .Values.saltmaster_srv_salt_volume_size }}
