apiVersion: v1
kind: Service
metadata:
  name: infra-salt-orchestrator
  labels:
    app: infra-salt-orchestrator
spec:
  selector:
    app: infra-salt-orchestrator
  ports:
  - protocol: TCP
    name: tcp-saltpublisher
    port: 4505
    targetPort: 4505
  - protocol: TCP
    name: tcp-saltreqserver
    port: 4506
    targetPort: 4506
  - protocol: TCP
    name: tcp-saltapiserver
    port: 8000
    targetPort: 8000
  - port: 443
    name: http-chisel
---
apiVersion: v1
kind: Service
metadata:
  name: salt-master
  labels:
    app: salt-master
spec:
  selector:
    app: salt-master
  ports:
  - protocol: TCP
    name: tcp-saltpublisher
    port: 4505
    targetPort: 4505
  - protocol: TCP
    name: tcp-saltreqserver
    port: 4506
    targetPort: 4506
  - protocol: TCP
    name: tcp-saltapiserver
    port: 8000
    targetPort: 8000
