{{- if eq .Values.global.generate_self_signed_cert true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rcr-istio-selfsigned-cert
spec:
  dnsNames:
    - rcr.{{ .Values.global.default_partner_console_domain }}
  secretName: rafay-container-registry-tls-secret-opaque
  duration: 87600h0m0s
  renewBefore: 12h0m0s
  issuerRef:
    name: self-signed-ca-cert
    kind: ClusterIssuer
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: rafay-container-registry-tls-secret-opaque
type: Opaque
data:
  tls.crt: {{ .Values.global.default_partner_console_cert }}
  tls.key: {{ .Values.global.default_partner_console_key }}
{{- end }}
