---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rafay-prompt
  name: rafay-prompt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rafay-prompt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rafay-prompt
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rafay-prompt
              topologyKey: kubernetes.io/hostname
      containers:
      - name: rafay-prompt
        image: "{{ .Values.rafay_prompt_image }}"
        env:
        - name: TEMP_PATH
          value: "/tmp"
        - name: DEV
          valueFrom:
            configMapKeyRef:
              name: rafay-prompt-config
              key: dev
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: rafay-prompt-config
              key:  api.port
        - name: AUTH_ADDR
          value: "authsrv:50011"
        - name: SENTRY_ADDR
          valueFrom:
            configMapKeyRef:
              name: rafay-prompt-config
              key: sentry.addr
        - name: ENABLE_PPROF
          valueFrom:
            configMapKeyRef:
              name: rafay-prompt-config
              key: enablePprof
        volumeMounts:
        - mountPath: /opt/rafay/.kube
          name: cache-volume
        - mountPath: /tmp
          name: tmp-volume
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }} 
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
---
{{- if .Values.global.ha_enabled }}
{{- if ne .Values.global.size "S" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: rafay-prompt
  name: rafay-prompt
spec:
  maxReplicas: {{ default "10" .Values.maxReplicas }}
{{- if eq .Values.global.ha_enabled true }}
  minReplicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  minReplicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rafay-prompt
  targetCPUUtilizationPercentage: 80
{{- end }}
{{- end }}