{{- if .Values.schedules }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "velero.fullname" $ }}-rafay-core-backup
  namespace: velero 
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $ }}
spec:
  schedule: "0 0 * * *" 
  template:
    {{- if .Values.global.velero.restic_enable }}
    defaultVolumesToRestic: true
    {{- else }}
    defaultVolumesToRestic: false
    {{- end }}
    includedNamespaces:
    - '*'
    excludedNamspaces:
    - velero
    includedResources:
    - '*'
    includeClusterResources: true
    snapshotVolumes: true
    storageLocation: default
    ttl: 168h0m0s 
    volumeSnapshotLocations:
    - default
{{- end }}

