{{- if eq .Values.global.generate_self_signed_cert true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-istio-selfsigned-cert
spec:
  dnsNames:
    - console.{{ .Values.global.default_partner_console_domain }}
  secretName: selfsigned-cert-tls-console
  duration: 19776h
  renewBefore: 12h
  issuerRef:
    name: {{ .Values.global.issuer_name | default "self-signed-ca-cert" }}
    kind: ClusterIssuer
{{- end }}
