apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "disable-mtls-kiali"
spec:
  host: "kiali.istio-system.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-tracing
spec:
  host: "tracing.istio-system.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-nexus
spec:
{{- if eq .Values.global.isCustomRegistry true}} 
  host: nexus-service.rafay-registry.svc.cluster.local
{{- else }}
  host: nexus-service.rafay-core.svc.cluster.local
{{- end }}  
  trafficPolicy:
    tls:
      mode: DISABLE
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: disable-mtls-nexus-docker
#spec:
#  host: nexus-service.rafay-core.svc.cluster.local
#  trafficPolicy:
#    tls:
#      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-prometheus
spec:
  host: prometheus.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-grafana
spec:
  host: grafana.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: infra-salt-orchestrator-destination
  namespace: rafay-core
spec:
  host: infra-salt-orchestrator-ext.rafay-core.svc.cluster.local
  subsets:
  - name: s0
    labels:
      statefulset.kubernetes.io/pod-name: infra-salt-orchestrator-0
  - name: s1
    labels:
      statefulset.kubernetes.io/pod-name: infra-salt-orchestrator-1
  - name: s2
    labels:
      statefulset.kubernetes.io/pod-name: infra-salt-orchestrator-2
