{{- if eq .Values.global.generate_self_signed_cert true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ops-console-istio-selfsigned-cert
spec:
  dnsNames:
    - ops-console.{{ .Values.global.default_partner_console_domain }}
  secretName: selfsigned-cert-tls-ops-console
  duration: 87600h
  renewBefore: 12h
  issuerRef:
    name: {{ .Values.global.issuer_name | default "self-signed-ca-cert" }}
    kind: ClusterIssuer
{{- end }}
