{{- if and .Values.global.generate_self_signed_cert .Values.global.external_metrics.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rafay-prometheus-istio-selfsigned-cert
spec:
  dnsNames:
    - rafay-prometheus.{{ .Values.global.default_partner_console_domain }}
  secretName: selfsigned-cert-tls-rafay-prometheus
  duration: 87600h
  renewBefore: 12h
  issuerRef:
    name: {{ .Values.global.issuer_name | default "self-signed-ca-cert" }}
    kind: ClusterIssuer
{{- end }}
