apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: random-passwords
    chart: {{ template "certificates.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  admin.db.password: {{ default (randAlphaNum 10) .Values.admin_db_password | b64enc | quote }}
  edge.db.password: {{ default (randAlphaNum 10) .Values.edge_db_password | b64enc | quote }}
  configv2.db.password: {{ default (randAlphaNum 10) .Values.config_v2_db_password | b64enc | quote }}
  scheduler.db.password: {{ default (randAlphaNum 10) .Values.global.scheduler_db_password | b64enc | quote }}
  keygen.db.password: {{ default (randAlphaNum 10) .Values.keygen_db_password | b64enc | quote }}
  pipeline.db.password: {{ default (randAlphaNum 10) .Values.pipeline_db_password | b64enc | quote }}
  events.db.password : {{ default (randAlphaNum 10) .Values.events_db_password | b64enc | quote }}

