apiVersion: v1
kind: Service
metadata:
  name: infra-scheduler
spec:
  ports:
    - name: grpc
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: infra-scheduler
  sessionAffinity: None
  type: ClusterIP
