apiVersion: v1
kind: Service
metadata:
  name: capi-controller-gke
spec:
  ports:
    - name: grpc
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: capi-controller-gke
  sessionAffinity: None
  type: ClusterIP
