apiVersion: v1
kind: ServiceAccount
metadata:
  name: capi-controller-gke-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-controller-gke-role
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    verbs:
    - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-controller-gke-rb
subjects:
  - kind: ServiceAccount
    name: capi-controller-gke-sa
    namespace: rafay-system
roleRef:
  kind: Role
  name: capi-controller-gke-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: capi-controller-gke
  name: capi-controller-gke
  namespace: rafay-core
spec:
  progressDeadlineSeconds: 600
  {{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
  {{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: capi-controller-gke
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capi-controller-gke
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - capi-controller-gke
              topologyKey: kubernetes.io/hostname
      serviceAccount: "capi-controller-gke-sa"
      containers:
      - env:
        - name: IS_SELF_HOSTED
          value: "true"
        - name: IS_SELF_SIGNED
          value: "true"
        - name: CLUSTER_SCHEDULER_HOST
          value: scheduler.rafay-core.svc.cluster.local
        - name: CLUSTER_SCHEDULER_PORT
          value: "5000"
        - name: IMAGES_VERSION
          value: "latest"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INFRA_RELAY_USER_HOST
          valueFrom:
            configMapKeyRef:
              key: infrarelay.user.host
              name: capi-controller-gke-configmap
        - name: SENTRY_ADDR
          valueFrom:
            configMapKeyRef:
              key: sentry.addr
              name: capi-controller-gke-configmap
        - name: NEXUS_URL
          valueFrom:
            configMapKeyRef:
              key: nexus.url
              name: capi-controller-gke-configmap
        - name: GITHUB_TOKEN
          valueFrom:
            configMapKeyRef:
              key: github.token
              name: capi-controller-gke-configmap 
        - name: CAPG_VERSION
          valueFrom:
            configMapKeyRef:
              key: capg.version
              name: capi-controller-gke-configmap
        - name: DOCKER_ADDR
          valueFrom:
            configMapKeyRef:
              key: docker.addr
              name: capi-controller-gke-configmap
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              key: redisAddr
              name: capi-controller-gke-configmap
        - name: CONTROLLER_RESOURCES_VERSION
          valueFrom:
            configMapKeyRef:
              key: contoller.resources.version
              name: capi-controller-gke-configmap
        image: {{.Values.capi_controller_gke_image }}
        imagePullPolicy: IfNotPresent
        name: capi-controller-gke
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }}
---
{{- if .Values.global.ha_enabled }}
{{- if ne .Values.global.size "S" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: capi-controller-gke
  name: capi-controller-gke
spec:
  maxReplicas: {{ default "10" .Values.maxReplicas }}
{{- if eq .Values.global.ha_enabled true }}
  minReplicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  minReplicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capi-controller-gke
  targetCPUUtilizationPercentage: 80
{{- end }}
{{- end }}