---
apiVersion: v1
kind: Service
metadata:
  name: rafay-cd-relay
spec:
  ports:
    - protocol: TCP
      name: tcp-relay
      port: 443
      targetPort: 443
    - protocol: TCP
      name: http-relay-monitoring
      port: 8003
      targetPort: 8003
  selector:
    app: rafay-cd-relay
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: rafay-cd-relay
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      app: rafay-cd-relay
