---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rafay-cd-relay
  name: rafay-cd-relay
spec:
{{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: rafay-cd-relay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rafay-cd-relay
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rafay-cd-relay
              topologyKey: kubernetes.io/hostname
      containers:
      - name: rafay-cd-relay
        args: ["--mode=cdrelay", "--log-level=3"]
        image: "{{ .Values.rafay_cd_relay_image }}"
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }} 
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RAFAY_RELAY_PEERSERVICE
          valueFrom:
            configMapKeyRef:
              name: rafay-cd-relay-config
              key:  sentry.peering.host
        - name: SENTRY_ADDR
          valueFrom:
            configMapKeyRef:
              name: rafay-cd-relay-config
              key:  sentry.addr
      
---
{{- if .Values.global.ha_enabled }}
{{- if ne .Values.global.size "S" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: rafay-cd-relay
  name: rafay-cd-relay
spec:
  maxReplicas: {{ default "10" .Values.maxReplicas }}
{{- if eq .Values.global.ha_enabled true }}
  minReplicas: {{ default "3" .Values.global.minReplicaCount }}
{{- else }}
  minReplicas: {{ default "1" .Values.global.minReplicaCount }}
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rafay-cd-relay
  targetCPUUtilizationPercentage: 80
{{- end }}
{{- end }}
