apiVersion: v1
kind: Service
metadata:
  name: frontend-opsconsole
  labels:
    app: frontend-opsconsole
spec:
  ports:
    - port: 8081
      name: http
      targetPort: 8081
  selector:
    app: frontend-opsconsole
