---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prometheus-k8s-cost-metrics
    app.kubernetes.io/version: 2.24.0
    prometheus: k8s-cost-metrics
  name: prometheus-k8s-cost-metrics
  namespace: rafay-core
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    app.kubernetes.io/name: prometheus-k8s-cost-metrics
    prometheus: k8s-cost-metrics
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
