---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/name: prometheus-k8s-cost-metrics
    app.kubernetes.io/version: 2.24.0
    prometheus: k8s-cost-metrics
  name: k8s-cost-metrics
  namespace: rafay-core
spec:
  affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - k8s-cost-metrics
              topologyKey: kubernetes.io/hostname
  evaluationInterval: 1m
  externalLabels:
    prometheus: rafay-infra/k8s
    prometheus_replica: prometheus-k8s-0
  externalUrl: {{ .Values.prometheus_costmetrics_external_url }}
  image: {{.Values.prometheus_image }}
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/name: prometheus-k8s-cost-metrics
      app.kubernetes.io/version: 2.24.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  query:
    lookbackDelta: 1m
  remoteRead:
  - readRecent: true
    remoteTimeout: 1m
# Below URL should be http, Just moved it to https for disabling it to send data to promscale. Revert to http, if needed to work.
    url: https://promscale-connector.rafay-core.svc.cluster.local:9201/read?db=monitoringdb&rp=shortterm&u=opsuser&p=Rafay!49
  replicas: 0
  {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
  resources:
    limits:
      cpu: "{{ .Values.cpu_limits }}"
      memory: "{{ .Values.memory_limits }}"
    requests:
      cpu: "{{ .Values.cpu_requests }}"
      memory: "{{ .Values.memory_requests }}"
  {{- end }}  
  retention: 24h
  scrapeInterval: 1m
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.24.0