apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: rafay-es
  namespace: rafay-core 
  annotations:
    "helm.sh/hook": post-install
spec:
  version: {{ .Values.version }}
  image: {{ .Values.image }}
  auth:
    fileRealm:
    - secretName: rafay-es-es-elastic-user
  nodeSets:
  - name: default
    count: {{ .Values.replicas }}
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 3Gi
              cpu: 1
            requests:
              memory: 400Mi
              cpu: 100m                     
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistance.size }}
        {{- if .Values.persistance.storageClass }}
        storageClassName: {{ .Values.persistance.storageClass }}
        {{- end }}
