{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sigv4-proxy.serviceAccountName" . }}
  labels:
    {{- include "sigv4-proxy.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.global.monitoring.integrations.amp.ingest_role_arn}}" 
  {{- end }}
{{- end }}
