---
# edge secret
apiVersion: v1
kind: Secret
metadata:
  name: edgesrv-secrets
type: Opaque
data:
  edge.db.user: {{ .Values.global.dbusers.edge_db_user | b64enc }}
  sendgrid.apikey: {{ .Values.global.secrets.sendgrid_apikey }}
  twilio.sid: {{ .Values.global.secrets.twilio_sid }}
  twilio.authtoken: {{ .Values.global.secrets.twilio_authtoken }}
  registry.user: {{ .Values.global.secrets.registry_user_name }}
  registry.password: {{ .Values.global.secrets.registry_user_password }}
  aws.access.key.id: {{ .Values.global.secrets.aws_access_key_id | default "ZHVtbXk=" }}
  aws.secret.access.key: {{ .Values.global.secrets.aws_secret_access_key | default "ZHVtbXk=" }}
  influx-pwd: {{ .Values.global.influx_pwd }}
  opsgenie-api-key: {{ .Values.global.opsgenie_api_key }}
  logmon-aws-access-keyid: {{ .Values.global.log_mon_aws_access_key_id }}
  logmon-aws-secret-key: {{ .Values.global.logmon_aws_secret_key }}
  alert-manager-yaml: {{ .Files.Get "alertmanager.yaml.j2" | b64enc }}
  clustertemplate.db.user: {{ .Values.global.dbusers.clustertemplate_db_user | b64enc }}
