{{- if and .Values.global.proxy.ip .Values.global.proxy.port }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy
  namespace: rafay-core
spec:
  hosts:
  - "{{ .Values.global.proxy.host }}"
  addresses:
  - "{{ .Values.global.proxy.ip}}/32"
  ports:
  - number: {{ .Values.global.proxy.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
{{- end }}
