apiVersion: v1
kind: Namespace
metadata:
  name: engine-agents
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine-agent-sa
  namespace: engine-agents
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: engine-agent
  name: engine-agent
  namespace: engine-agents
spec:
  {{- if eq .Values.global.ha_enabled true }}
  replicas: {{ default "3" .Values.global.minReplicaCount }}
  {{- else }}
  replicas: {{ default "1" .Values.global.minReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: engine-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: engine-agent
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - engine-agent
              topologyKey: kubernetes.io/hostname            
      serviceAccount: engine-agent-sa
      containers:
      - name: engine-agent
        image: {{ .Values.global.envmgr_image }}
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }} 
        env:
        - name: ENGINE_ENABLE_AGENT
          valueFrom:
            configMapKeyRef:
              key: engine.enable_agent
              name: engine-agent-cm
        - name: ENGINE_AGENT_GLOBAL
          valueFrom:
            configMapKeyRef:
              key: engine.engine_agent.global
              name: engine-agent-cm
        - name: ENGINE_AGENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: engine.engine_agent.endpoint
              name: engine-agent-cm
        - name: ENGINE_AGENT_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ENGINE_AGENT_SKIP_TLS_VERIFY
          value: "true"
