apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine-worker-sa
  namespace: rafay-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: engine-worker-role
  namespace: rafay-core
rules:
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engine-worker-rolebinding
  namespace: rafay-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: engine-worker-role
subjects:
  - kind: ServiceAccount
    name: engine-worker-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: engine-worker
  name: engine-worker
  namespace: rafay-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.100.0.0/16"
      labels:
        app: engine-worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - engine-worker
              topologyKey: kubernetes.io/hostname            
      serviceAccount: engine-worker-sa
      containers:
      - name: engine-worker
        image: {{ .Values.global.envmgr_image }}
        {{- if or (eq .Values.global.ha_enabled true) (eq .Values.global.size "S") (eq .Values.global.size "M") (eq .Values.global.size "L") }}
        resources:
          limits:
            cpu: "{{ .Values.cpu_limits }}"
            memory: "{{ .Values.memory_limits }}"
          requests:
            cpu: "{{ .Values.cpu_requests }}"
            memory: "{{ .Values.memory_requests }}"
        {{- end }}
        env:
        - name: ENGINE_ENABLE_WORKER
          valueFrom:
            configMapKeyRef:
              key: engine.enable_worker
              name: engine-worker-cm
        - name: ENGINE_WORKER_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              key: engine.engine_worker.redis_addr
              name: engine-worker-cm
        - name: HELPERS_ADDR
          valueFrom:
            configMapKeyRef:
              key: helpers.addr
              name: engine-worker-cm
        - name: ENGINE_WORKER_ENGINE_API_RPC_ADDR
          valueFrom:
            configMapKeyRef:
              key: engine.engine_worker.engine_api_rpc_addr
              name: engine-worker-cm
        - name: LEADER_ELECTION_LEADER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LEADER_ELECTION_LEASE_LOCK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /livez
            port: 15010
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
          initialDelaySeconds: 5
