---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rafay-config-configmap
data:
  rpcPort: "7000"
  apiPort: "9000"
  dbName: "configv2db"
  dbUser: {{ .Values.global.dbusers.configv2_db_user | quote }}
  dbAddr: "postgres-admin:5432"
  schedulerAddr: "scheduler:5000"
  pipelineAddr: "rafay-pipeline:7000"
  secretPath: "/opt/rcloud/certs"
  prod: "true"
  dev: "false"
  enableEngineAgent: "true"
  authAddr: "authsrv:50011"
  enablePprof: "true"
  cryptoAddr: "cryptosvc:50505"
  sentry.addr: "rafay-sentry:7000"
  infrarelay.user.host: "*.user.infrarelay.{{ .Values.global.default_partner_console_domain }}:443"
  sentry.bootstrap.addr: "console.{{ .Values.global.default_partner_console_domain }}:443"
  cdagent.core.addr: "rafay-cd-agent:7000"
  cdrelay.user.host: "*.user.cdrelay.{{ .Values.global.default_partner_console_domain }}:443"
  fluentd.aggregator.addr: "fluentd-aggr.{{ .Values.global.default_partner_console_domain }}"
  internal.trigger.endpoint: "http://rafay-pipeline:9001/v2/pipeline/subscription/internal,http://rafay-hub:9001/v3/hub/subscription/internal"
  aws_s3_cb_bucket_region: "{{ .Values.global.aws_s3_region}}"
  aws_s3_cb_bucket: "{{ .Values.global.aws_s3_cb_bucket}}"
  redisAddr: "{{ .Values.global.redis_endpoint  }}.rafay-core.svc.cluster.local:6379"
  eaasAddr: eaas-api:6000
  engineAddr: engine-api:5000
  repository_fqdn: "ops-console.{{.Values.global.default_partner_console_domain}}"
  num_max_cd_agent_health_check_workers: "160"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rafay-config-imageoverride
data:
  # Configuration values can be set as key-value properties
  VAULTINIT_IMAGE: {{ (splitList "/" .Values.global.vaultinit_image) | last | quote }}
  SECRETSTOREHOOK_IMAGE: {{ (splitList "/" .Values.global.secretstorehook_image) | last | quote }}
  CONTROLLER_IMAGE: {{ (splitList "/" .Values.global.cluster_controller_image) | last | quote }}
  CONNECTOR_IMAGE: {{ (splitList "/" .Values.global.cluster_connector_image) | last | quote }}
  CDAGENT_IMAGE: {{ (splitList "/" .Values.global.rafay_cd_agent_image) | last | quote }}
  EDGECLIENT_IMAGE: {{ (splitList "/" .Values.global.edge_client_image) | last | quote }}
  RELAYAGENT_IMAGE: {{ (splitList "/" .Values.global.rafay_relay_agent_image) | last | quote }}
  busyBoxImage: {{ (splitList "/" .Values.global.busyBoxImage) | last | quote }}
  CDAGENT_DOCKER_IMAGE: {{ (splitList "/" .Values.global.rafay_cd_agent_docker_image) | last | quote }}
