---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rafay-config-role
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    verbs:
    - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
